# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 370cc106efe75091c9c2293be3e9123891c69576ed24383e7030e4c8ba5db573dcdb2e5fced69618d96d311ef1438bc77c2b2fc909a2bd83261ba10d47a01141

test:
  secret_key_base: be72f119172ced2cc36e74fe0979fa6d08f87689107c43b961d3d56aaa8155924b210fc5bcfdbb2df54e238aed6a58597b7acd935ad669e05f7b7b816c4fd49c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
